[tool.poetry]
name = "prekolk"
version = "0.1.0"
description = ""
authors = ["Michael Fedorov <mikhailfedorov1939@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.10"
hexlet-immutable-fs-trees = "^0.1.8"
Flask = "^2.2.2"

[tool.poetry.dev-dependencies]
pytest = "^7.1"
flake8 = "^4.0.1"
ipython = "^8.4.0"
pytest-cov = "^3.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
